"""create ticketing schema and all tables

Revision ID: e3ca0a118dbf
Revises: 
Create Date: 2026-04-20 15:42:21.432622

# Safe to run: only creates/modifies ticketing.* tables
# Does NOT touch: grievances, complainants, or any existing public.* table
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3ca0a118dbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organization_id'),
    schema='ticketing'
    )
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('role_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_key'),
    schema='ticketing'
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    schema='ticketing'
    )
    op.create_table('workflow_definitions',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id'),
    sa.UniqueConstraint('workflow_key'),
    schema='ticketing'
    )
    op.create_table('locations',
    sa.Column('location_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('parent_location', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['ticketing.organizations.organization_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_location'], ['ticketing.locations.location_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('location_code'),
    schema='ticketing'
    )
    op.create_table('user_roles',
    sa.Column('user_role_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('location_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['ticketing.roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_role_id'),
    schema='ticketing'
    )
    op.create_index('idx_user_roles_user_org_loc', 'user_roles', ['user_id', 'organization_id', 'location_code'], unique=False, schema='ticketing')
    op.create_table('workflow_assignments',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('location_code', sa.String(length=64), nullable=True),
    sa.Column('project_code', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['ticketing.workflow_definitions.workflow_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id'),
    schema='ticketing'
    )
    op.create_index('idx_workflow_assign_org_loc_pri', 'workflow_assignments', ['organization_id', 'location_code', 'project_code', 'priority'], unique=False, schema='ticketing')
    op.create_table('workflow_steps',
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('assigned_role_key', sa.String(length=64), nullable=False),
    sa.Column('response_time_hours', sa.Integer(), nullable=True),
    sa.Column('resolution_time_days', sa.Integer(), nullable=True),
    sa.Column('stakeholders', sa.JSON(), nullable=True),
    sa.Column('expected_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['ticketing.workflow_definitions.workflow_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id'),
    schema='ticketing'
    )
    op.create_index('idx_workflow_steps_workflow_order', 'workflow_steps', ['workflow_id', 'step_order'], unique=False, schema='ticketing')
    op.create_table('tickets',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=64), nullable=False),
    sa.Column('complainant_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('chatbot_id', sa.String(length=64), nullable=False),
    sa.Column('grievance_summary', sa.Text(), nullable=True),
    sa.Column('grievance_categories', sa.Text(), nullable=True),
    sa.Column('grievance_location', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('location_code', sa.String(length=64), nullable=True),
    sa.Column('project_code', sa.String(length=64), nullable=True),
    sa.Column('status_code', sa.String(length=32), nullable=False),
    sa.Column('current_workflow_id', sa.String(length=36), nullable=False),
    sa.Column('current_step_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('is_seah', sa.Boolean(), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=128), nullable=True),
    sa.Column('assigned_role_id', sa.String(length=36), nullable=True),
    sa.Column('step_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['current_step_id'], ['ticketing.workflow_steps.step_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_workflow_id'], ['ticketing.workflow_definitions.workflow_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ticket_id'),
    schema='ticketing'
    )
    op.create_index('idx_tickets_assigned_to', 'tickets', ['assigned_to_user_id'], unique=False, schema='ticketing')
    op.create_index('idx_tickets_current_workflow', 'tickets', ['current_workflow_id', 'current_step_id'], unique=False, schema='ticketing')
    op.create_index('idx_tickets_grievance_id', 'tickets', ['grievance_id'], unique=False, schema='ticketing')
    op.create_index('idx_tickets_is_seah', 'tickets', ['is_seah'], unique=False, schema='ticketing')
    op.create_index('idx_tickets_org_loc_status', 'tickets', ['organization_id', 'location_code', 'status_code'], unique=False, schema='ticketing')
    op.create_table('ticket_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('old_status_code', sa.String(length=32), nullable=True),
    sa.Column('new_status_code', sa.String(length=32), nullable=True),
    sa.Column('old_assigned_to', sa.String(length=128), nullable=True),
    sa.Column('new_assigned_to', sa.String(length=128), nullable=True),
    sa.Column('workflow_step_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticketing.tickets.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    schema='ticketing'
    )
    op.create_index('idx_ticket_events_assigned_seen', 'ticket_events', ['assigned_to_user_id', 'seen'], unique=False, schema='ticketing')
    op.create_index('idx_ticket_events_event_type', 'ticket_events', ['event_type'], unique=False, schema='ticketing')
    op.create_index('idx_ticket_events_ticket_id', 'ticket_events', ['ticket_id', 'created_at'], unique=False, schema='ticketing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ticket_events_ticket_id', table_name='ticket_events', schema='ticketing')
    op.drop_index('idx_ticket_events_event_type', table_name='ticket_events', schema='ticketing')
    op.drop_index('idx_ticket_events_assigned_seen', table_name='ticket_events', schema='ticketing')
    op.drop_table('ticket_events', schema='ticketing')
    op.drop_index('idx_tickets_org_loc_status', table_name='tickets', schema='ticketing')
    op.drop_index('idx_tickets_is_seah', table_name='tickets', schema='ticketing')
    op.drop_index('idx_tickets_grievance_id', table_name='tickets', schema='ticketing')
    op.drop_index('idx_tickets_current_workflow', table_name='tickets', schema='ticketing')
    op.drop_index('idx_tickets_assigned_to', table_name='tickets', schema='ticketing')
    op.drop_table('tickets', schema='ticketing')
    op.drop_index('idx_workflow_steps_workflow_order', table_name='workflow_steps', schema='ticketing')
    op.drop_table('workflow_steps', schema='ticketing')
    op.drop_index('idx_workflow_assign_org_loc_pri', table_name='workflow_assignments', schema='ticketing')
    op.drop_table('workflow_assignments', schema='ticketing')
    op.drop_index('idx_user_roles_user_org_loc', table_name='user_roles', schema='ticketing')
    op.drop_table('user_roles', schema='ticketing')
    op.drop_table('locations', schema='ticketing')
    op.drop_table('workflow_definitions', schema='ticketing')
    op.drop_table('settings', schema='ticketing')
    op.drop_table('roles', schema='ticketing')
    op.drop_table('organizations', schema='ticketing')
    # ### end Alembic commands ###
