"""
Database table configuration and lookup data.

This module contains database table metadata and fallback data for seeding.
The database is the authoritative source of truth for lookup tables.
Python configuration is used for initial seeding and fallback values.
"""

from typing import Dict, Any, List

############################
# FALLBACK DATA FOR SEEDING
############################

# These are used ONLY for initial database seeding and fallback values
# The database is the authoritative source of truth

# Task Status Fallback Data (for seeding)
TASK_STATUS_SEED_DATA = [
    {"code": "started", "name": "Started", "description": "Task is started"},
    {"code": "SUCCESS", "name": "Success", "description": "Task is successful"},
    {"code": "failed", "name": "Failed", "description": "Task is failed"},
    {"code": "retrying", "name": "Retrying", "description": "Task is retrying"}
]

# Grievance Status Fallback Data (for seeding)
GRIEVANCE_STATUS_SEED_DATA = [
    {"code": "SUBMITTED", "name_en": "Submitted", "name_ne": "जमा भएको", "description_en": "Grievance has been submitted by the complainant", "description_ne": "गुनासो जमा भएको छ"},
    {"code": "UNDER_EVALUATION", "name_en": "Under Evaluation", "name_ne": "समीक्षा भइरहेको", "description_en": "Grievance is under evaluation by assigned officer", "description_ne": "गुनासो समीक्षा भइरहेको छ"},
    {"code": "ESCALATED", "name_en": "Escalated", "name_ne": "विस्तारित भएको", "description_en": "Grievance has been escalated to higher authority", "description_ne": "गुनासो विस्तारित भएको छ"},
    {"code": "RESOLVED", "name_en": "Resolved", "name_ne": "समाधान भएको", "description_en": "Grievance has been resolved by the officer", "description_ne": "गुनासो समाधान भएको छ"},
    {"code": "DENIED", "name_en": "Denied", "name_ne": "अस्वीकृत", "description_en": "Grievance has been denied", "description_ne": "गुनासो अस्वीकृत भएको छ"},
    {"code": "DISPUTED", "name_en": "Disputed", "name_ne": "विरोध भएको", "description_en": "Grievance resolution is not accepted by the complainant who requests the case to be reopened", "description_ne": "गुनासो विरोध भएको छ"},
    {"code": "CLOSED", "name_en": "Closed", "name_ne": "बन्द भएको", "description_en": "Grievance case is closed", "description_ne": "गुनासो केस बन्द भएको छ"}
]

# Grievance Classification Status Fallback Data (for seeding)
GRIEVANCE_CLASSIFICATION_STATUS_SEED_DATA = [
    {"code": "LLM_generated", "name": "LLM Generated", "description": "Grievance classification is generated by LLM"},
    {"code": "LLM_failed", "name": "LLM Failed", "description": "Grievance classification is failed by LLM"},
    {"code": "LLM_error", "name": "LLM Error", "description": "Grievance classification is in error by LLM"},
    {"code": "complainant_confirmed", "name": "Complainant Confirmed", "description": "Grievance classification is confirmed by complainant"},
    {"code": "officer_confirmed", "name": "Officer Confirmed", "description": "Grievance classification is confirmed by officer"},
    {"code": "slot_skipped", "name": "slot_skipped", "description": "slot_skipped"},
    {"code": "REVIEWING", "name": "Reviewing", "description": "Temporary status used to review the classification results in the App"}
]

# Transcription Processing Status Fallback Data (for seeding)
TRANSCRIPTION_PROCESSING_STATUS_SEED_DATA = [
    {"code": "PROCESSING", "name": "Processing", "description": "Transcription is in progress"},
    {"code": "COMPLETED", "name": "Completed", "description": "Transcription is completed"},
    {"code": "FAILED", "name": "Failed", "description": "Transcription is failed"},
    {"code": "FOR_VERIFICATION", "name": "For Verification", "description": "Transcription is for verification"},
    {"code": "VERIFICATION_IN_PROGRESS", "name": "Verification In Progress", "description": "Transcription is in verification by dedicated team"},
    {"code": "VERIFIED", "name": "Verified", "description": "Transcription is verified by dedicated team"},
    {"code": "VERIFIED_AND_AMENDED", "name": "Verified and Amended", "description": "Transcription is verified and amended by dedicated team"}
]

############################
# FIELD CONFIGURATION
############################

# Field names for database operations
FIELD_NAMES = [
    'grievance_description',
    'complainant_full_name', 
    'complainant_phone',
    'complainant_email',
    'complainant_province',
    'complainant_district',
    'complainant_municipality',
    'complainant_ward',
    'complainant_village',
    'complainant_address',
    'grievance_categories',
    'grievance_summary',
    'grievance_description_en'
]

# Field descriptions
FIELD_DESCRIPTIONS = {
    'grievance_description': 'Grievance details',
    'complainant_full_name': 'User full name',
    'complainant_phone': 'User phone number',
    'complainant_email': 'User email address',
    'complainant_province': 'User province',
    'complainant_district': 'User district',
    'complainant_municipality': 'User municipality',
    'complainant_ward': 'User ward number',
    'complainant_village': 'User village',
    'complainant_address': 'User address',
    'grievance_categories': 'Grievance categories',
    'grievance_summary': 'Grievance summary',
    'grievance_description_en': 'Grievance description in English'
}

# Field names for seeding
FIELD_NAMES_SEED_DATA = [
    {"field_name": "grievance_description", "description": "Grievance details"},
    {"field_name": "complainant_full_name", "description": "User full name"},
    {"field_name": "complainant_phone", "description": "User phone number"},
    {"field_name": "complainant_email", "description": "User email address"},
    {"field_name": "complainant_province", "description": "User province"},
    {"field_name": "complainant_district", "description": "User district"},
    {"field_name": "complainant_municipality", "description": "User municipality"},
    {"field_name": "complainant_ward", "description": "User ward number"},
    {"field_name": "complainant_village", "description": "User village"},
    {"field_name": "complainant_address", "description": "User address"},
    {"field_name": "grievance_categories", "description": "Grievance categories"},
    {"field_name": "grievance_summary", "description": "Grievance summary"},
    {"field_name": "grievance_description_en", "description": "Grievance description in English"}
]

############################
# TIMELINE CONFIGURATION
############################

# Default timeline values for status updates (in days)
DEFAULT_TIMELINE_DAYS = 15

# Timeline configuration for different status combinations
# This can be extended to include more specific timelines
TIMELINE_CONFIG = {
    "default": DEFAULT_TIMELINE_DAYS,
    "high_priority_multiplier": 1.0,  # No change for high priority
    "sensitive_issues_multiplier": 1.0  # No change for sensitive issues
}

############################
# DATABASE TABLE METADATA
############################

# Table creation order (dependencies first)
TABLE_CREATION_ORDER = [
    'grievance_statuses',
    'processing_statuses', 
    'task_statuses',
    'grievance_classification_statuses',
    'field_names',
    'complainants',
    'office_management',
    'office_municipality_ward',
    'office_user',
    'tasks',
    'grievances',
    'task_entities',
    'grievance_status_history',
    'grievance_history',
    'file_attachments',
    'grievance_voice_recordings',
    'grievance_transcriptions',
    'grievance_translations',
    'status_update_timeline'
]

# Table dependencies mapping
TABLE_DEPENDENCIES = {
    'grievances': ['complainants', 'grievance_statuses'],
    'grievance_history': ['grievances'],
    'grievance_status_history': ['grievances', 'grievance_statuses'],
    'file_attachments': ['grievances'],
    'grievance_voice_recordings': ['grievances'],
    'grievance_transcriptions': ['grievance_voice_recordings'],
    'grievance_translations': ['grievance_transcriptions'],
    'office_municipality_ward': ['office_management'],
    'office_user': ['office_management'],
    'tasks': ['task_statuses'],
    'task_entities': ['tasks']
}

############################
# FIELD CONFIGURATION
############################

# Field names for database operations
FIELD_NAMES = [
    'grievance_description',
    'complainant_full_name', 
    'complainant_phone',
    'complainant_email',
    'complainant_province',
    'complainant_district',
    'complainant_municipality',
    'complainant_ward',
    'complainant_village',
    'complainant_address',
    'grievance_categories',
    'grievance_summary',
    'grievance_description_en'
]

# Field descriptions
FIELD_DESCRIPTIONS = {
    'grievance_description': 'Grievance details',
    'complainant_full_name': 'User full name',
    'complainant_phone': 'User phone number',
    'complainant_email': 'User email address',
    'complainant_province': 'User province',
    'complainant_district': 'User district',
    'complainant_municipality': 'User municipality',
    'complainant_ward': 'User ward number',
    'complainant_village': 'User village',
    'complainant_address': 'User address',
    'grievance_categories': 'Grievance categories',
    'grievance_summary': 'Grievance summary',
    'grievance_description_en': 'Grievance description in English'
}

############################
# DATABASE LOOKUP SERVICE
############################

class DatabaseLookupService:
    """
    Service for accessing lookup data from the database.
    This is the authoritative source of truth for all lookup tables.
    """
    
    def __init__(self, db_manager):
        self.db_manager = db_manager
        self._cache = {}
        self._cache_loaded = False
    
    def _load_cache(self):
        """Load all lookup data into memory cache."""
        if self._cache_loaded:
            return
            
        try:
            # Load grievance statuses
            self._cache['grievance_statuses'] = self.db_manager.execute_query(
                "SELECT * FROM grievance_statuses ORDER BY sort_order, status_code"
            )
            
            # Load task statuses  
            self._cache['task_statuses'] = self.db_manager.execute_query(
                "SELECT * FROM task_statuses ORDER BY task_status_code"
            )
            
            # Load processing statuses
            self._cache['processing_statuses'] = self.db_manager.execute_query(
                "SELECT * FROM processing_statuses ORDER BY status_code"
            )
            
            # Load field names
            self._cache['field_names'] = self.db_manager.execute_query(
                "SELECT * FROM field_names ORDER BY field_name"
            )
            
            self._cache_loaded = True
            
        except Exception as e:
            # Fallback to seed data if database is unavailable
            self._cache = {
                'grievance_statuses': GRIEVANCE_STATUS_SEED_DATA,
                'task_statuses': TASK_STATUS_SEED_DATA,
                'processing_statuses': TRANSCRIPTION_PROCESSING_STATUS_SEED_DATA,
                'field_names': FIELD_NAMES_SEED_DATA
            }
            self._cache_loaded = True
    
    def get_grievance_statuses(self) -> List[Dict[str, Any]]:
        """Get all grievance statuses from database."""
        self._load_cache()
        return self._cache.get('grievance_statuses', [])
    
    def get_task_statuses(self) -> List[Dict[str, Any]]:
        """Get all task statuses from database."""
        self._load_cache()
        return self._cache.get('task_statuses', [])
    
    def get_processing_statuses(self) -> List[Dict[str, Any]]:
        """Get all processing statuses from database."""
        self._load_cache()
        return self._cache.get('processing_statuses', [])
    
    def get_field_names(self) -> List[Dict[str, Any]]:
        """Get all field names from database."""
        self._load_cache()
        return self._cache.get('field_names', [])
    
    def get_grievance_status_by_code(self, status_code: str) -> Dict[str, Any]:
        """Get a specific grievance status by code."""
        statuses = self.get_grievance_statuses()
        for status in statuses:
            if status.get('status_code') == status_code:
                return status
        return {}
    
    def get_task_status_by_code(self, status_code: str) -> Dict[str, Any]:
        """Get a specific task status by code."""
        statuses = self.get_task_statuses()
        for status in statuses:
            if status.get('task_status_code') == status_code:
                return status
        return {}
    
    def refresh_cache(self):
        """Refresh the cache from database."""
        self._cache_loaded = False
        self._cache = {}
        self._load_cache()

############################
# UTILITY FUNCTIONS
############################

def get_table_dependencies(table_name: str) -> List[str]:
    """Get dependencies for a specific table."""
    return TABLE_DEPENDENCIES.get(table_name, [])

def get_creation_order() -> List[str]:
    """Get the order in which tables should be created."""
    return TABLE_CREATION_ORDER.copy()

def get_seed_data() -> Dict[str, List[Dict[str, Any]]]:
    """Get all seed data for database initialization."""
    return {
        'grievance_statuses': GRIEVANCE_STATUS_SEED_DATA,
        'task_statuses': TASK_STATUS_SEED_DATA,
        'processing_statuses': TRANSCRIPTION_PROCESSING_STATUS_SEED_DATA,
        'field_names': FIELD_NAMES_SEED_DATA
    }
