recipe: default.v1
assistant_id: 20241128-101605-happy-jail
language: en

pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.2

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 12
    epochs: 100
    constrain_similarities: true
  - name: "actions.custom_policy.PreviousStatePolicy"
