services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/webchat_rest_compose_aws.conf:/etc/nginx/conf.d/default.conf:ro
      - ./channels/REST_webchat:/app/channels/REST_webchat:ro
      - ./channels/shared:/app/channels/shared:ro
      - ./deployment/certbot/www:/var/www/certbot:ro
      - ./deployment/certbot/conf:/etc/letsencrypt:ro
