version: '3.8'

services:
  rasa-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasa_server
    ports:
      - "5005:5005"  # Expose the Rasa server API port
      - "5000:5000"  # Expose the Rasa server UI port
    volumes:
      - .:/app  # Mount your project directory into the container
      - ./models:/app/models  # Mount the trained models to the container
      - ./logs:/app/logs  # Sync logs between local and container
      - ./domain:/app/domain
      - ./data:/app/data
      - ./config.yml:/app/config.yml
      - ./start_train.sh:/app/start_train.sh
      - ./start.sh:/app/start.sh

    depends_on:
      - action-server  # Ensure the action server starts before the Rasa server
      - postgres  # Ensure the database starts before the Rasa server
    entrypoint: ["bash", "/app/start.sh"]
    command: []
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:5005/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  action-server:
    user: "root"  # Ensures the container runs as root
    image: rasa/rasa-sdk:latest  # Use the Rasa SDK for custom actions
    container_name: action_server
    ports:
      - "5055:5055"  # Expose the action server port
    volumes:
      - ./actions:/app/actions  # Mount your custom actions folder
      - ./logs:/app/logs  # Sync logs between local and container
    environment:
      - PYTHONUNBUFFERED=1  # Optional: Improves log readability
    build:
      context: .
      dockerfile: Dockerfile.actions
    entrypoint: ["rasa", "run", "actions", "--actions", "actions", "--port", "5055"]

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5055/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:13  # PostgreSQL version 13
    container_name: postgres
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
    environment:
      POSTGRES_USER: rasa_user
      POSTGRES_PASSWORD: rasa_password
      POSTGRES_DB: rasa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:
