version: '1.0'
slots:
  language_code:
    type: categorical
    default: null
    values:
    - en
    - ne
  complainant_province:
    type: text
    default: Koshi
  complainant_district:
    type: text
    default: Jhapa
  story_main:
    type: categorical
    default: null
    values:
    - status_check
    - new_grievance
    - new_complainant
    - modify_grievance
    - modify_contact
  grievance_id:
    type: text
    default: null
  complainant_id:
    type: text
    default: null
  grievance_sensitive_issue:
    type: bool
    default: false
  grievance_description:
    type: text
    default: null
  grievance_new_detail:
    type: text
    default: null
  grievance_description_status:
    type: text
    default: null
  requested_slot:
    type: text
    default: null
  skip_validation_needed:
    type: bool
    default: null
  skipped_detected_text:
    type: text
    default: null
form_slots:
  form_grievance:
    required_slots:
    - grievance_new_detail
