"""
ticketing.tickets and ticketing.ticket_events

PII rules (CLAUDE.md — LOCKED):
- NO FK into public.* tables
- NO PII stored — complainant name/phone/email never in ticketing.*
- grievance_id / complainant_id are plain VARCHAR string references only
- grievance_summary, grievance_categories, grievance_location cached at creation (non-PII)
- session_id stored for orchestrator POST /message notifications
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _uuid() -> str:
    return str(uuid.uuid4())


class Ticket(Base):
    __tablename__ = "tickets"
    __table_args__ = (
        Index("idx_tickets_grievance_id", "grievance_id"),
        Index("idx_tickets_org_loc_status", "organization_id", "location_code", "status_code"),
        Index("idx_tickets_assigned_to", "assigned_to_user_id"),
        Index("idx_tickets_current_workflow", "current_workflow_id", "current_step_id"),
        Index("idx_tickets_is_seah", "is_seah"),
        {"schema": "ticketing"},
    )

    ticket_id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)

    # ── Links to chatbot data — string refs, NO FK into public.* ──
    grievance_id: Mapped[str] = mapped_column(String(64), nullable=False)
    complainant_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    session_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    chatbot_id: Mapped[str] = mapped_column(String(64), nullable=False, default="nepal_grievance_bot")

    # ── Non-PII grievance data cached at creation (CLAUDE.md rule 4) ──
    grievance_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    grievance_categories: Mapped[str | None] = mapped_column(Text, nullable=True)
    grievance_location: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Source / scoping ──
    country_code: Mapped[str] = mapped_column(String(8), nullable=False, default="NP")
    organization_id: Mapped[str] = mapped_column(String(64), nullable=False)
    location_code: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # project_id replaces project_code — proper FK to ticketing.projects
    project_id: Mapped[str | None] = mapped_column(
        String(64),
        ForeignKey("ticketing.projects.project_id", ondelete="SET NULL"),
        nullable=True,
    )
    # project_code kept for backwards compat during transition; deprecated — use project_id
    project_code: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # ── Status & workflow ──
    status_code: Mapped[str] = mapped_column(String(32), nullable=False, default="OPEN")
    current_workflow_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("ticketing.workflow_definitions.workflow_id", ondelete="RESTRICT"),
        nullable=False,
    )
    current_step_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("ticketing.workflow_steps.step_id", ondelete="SET NULL"),
        nullable=True,
    )
    priority: Mapped[str] = mapped_column(String(32), nullable=False, default="NORMAL")

    # ── SEAH flag — DB-level visibility filter ──
    is_seah: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # ── Assignment ──
    assigned_to_user_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    assigned_role_id: Mapped[str | None] = mapped_column(String(36), nullable=True)

    # ── SLA tracking ──
    step_started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    sla_breached: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # ── LLM-generated content ──
    # ai_summary_en: findings digest generated by generate_findings Celery task.
    # Visible to grc_chair, adb_*, super_admin — hidden from L1/L2 field officers.
    ai_summary_en: Mapped[str | None] = mapped_column(Text, nullable=True)
    ai_summary_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Soft delete ──
    is_deleted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # ── Audit ──
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_now)
    created_by_user_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_now, onupdate=_now)
    updated_by_user_id: Mapped[str | None] = mapped_column(String(128), nullable=True)

    events: Mapped[list["TicketEvent"]] = relationship(
        "TicketEvent", back_populates="ticket",
        order_by="TicketEvent.created_at", lazy="select",
    )
    current_workflow: Mapped["WorkflowDefinition"] = relationship(  # type: ignore[name-defined]
        "WorkflowDefinition", foreign_keys=[current_workflow_id], lazy="select"
    )
    current_step: Mapped["WorkflowStep | None"] = relationship(  # type: ignore[name-defined]
        "WorkflowStep", foreign_keys=[current_step_id], lazy="select"
    )


class TicketEvent(Base):
    """Immutable append-only log. Powers audit trail, case timeline, and notification badge."""

    __tablename__ = "ticket_events"
    __table_args__ = (
        Index("idx_ticket_events_ticket_id", "ticket_id", "created_at"),
        Index("idx_ticket_events_event_type", "event_type"),
        Index("idx_ticket_events_assigned_seen", "assigned_to_user_id", "seen"),
        {"schema": "ticketing"},
    )

    event_id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    ticket_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("ticketing.tickets.ticket_id", ondelete="CASCADE"),
        nullable=False,
    )
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)
    old_status_code: Mapped[str | None] = mapped_column(String(32), nullable=True)
    new_status_code: Mapped[str | None] = mapped_column(String(32), nullable=True)
    old_assigned_to: Mapped[str | None] = mapped_column(String(128), nullable=True)
    new_assigned_to: Mapped[str | None] = mapped_column(String(128), nullable=True)
    workflow_step_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    payload: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    # Notification badge: seen=False counts toward officer's unread badge
    seen: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    assigned_to_user_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_now)
    created_by_user_id: Mapped[str | None] = mapped_column(String(128), nullable=True)

    # ── SEAH privacy handoff fields (seah-privacy-worktree-handoff.md) ──────────
    # actor_role: role key snapshotted at write time — audit correlation + UI role bubbles
    actor_role: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # case_sensitivity: 'standard'|'seah' — audit filtering without joining to tickets
    case_sensitivity: Mapped[str] = mapped_column(String(16), nullable=False, default="standard")
    # summary_regen_required: True → LLM summary pipeline must regenerate before next view
    summary_regen_required: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    ticket: Mapped["Ticket"] = relationship("Ticket", back_populates="events")
